# Generated by Django 2.2.13 on 2023-04-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.IntegerField(null=True),
        ),
    ]
